version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - run: apt-get install apt -y; add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial; apt-get update -y; true
      - run: apt-get install software-properties-common python-software-properties; true
      - run: apt-get install qt510-meta-full -y; /opt/qt510/bin/qt510-env.sh 
      - checkout
      - run: qmake; make
          
